"""add ondelete rules

Revision ID: d335c7d2b050
Revises: 9d4042b94b7e
Create Date: 2026-04-27 16:40:34.857643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd335c7d2b050'
down_revision: Union[str, Sequence[str], None] = '9d4042b94b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_user_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_room_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('room_photos_room_id_fkey'), 'room_photos', type_='foreignkey')
    op.create_foreign_key(None, 'room_photos', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rooms_owner_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['owner_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('tag_rooms_tag_id_fkey'), 'tag_rooms', type_='foreignkey')
    op.drop_constraint(op.f('tag_rooms_room_id_fkey'), 'tag_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'tag_rooms', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_rooms', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'tag_rooms', type_='foreignkey')
    op.drop_constraint(None, 'tag_rooms', type_='foreignkey')
    op.create_foreign_key(op.f('tag_rooms_room_id_fkey'), 'tag_rooms', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('tag_rooms_tag_id_fkey'), 'tag_rooms', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_owner_id_fkey'), 'rooms', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'room_photos', type_='foreignkey')
    op.create_foreign_key(op.f('room_photos_room_id_fkey'), 'room_photos', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_room_id_fkey'), 'reviews', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'])
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_user_id_fkey'), 'bookings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
